import { IStory } from "@/types/API";

export const newsAPI: IStory[] = [
  {
    "id": "d3573dfa-a0ae-48a4-8ffd-99c7f8838764",
    "title": "Stephen Hawking has died",
    "user_id": "bd5bd470-17e7-4879-890e-8d38fedde4d6",
    "user_name": "Cogito",
    "created_at": "2018-03-14T03:50:30Z",
    "url_ref": "http://www.bbc.com/news/uk-43396008",
    "content": null,
    "comment_count": 436,
    "upvote_count": 6015
  },
  {
    "id": "29c89b82-7fab-4e67-8ba4-97c5a853233b",
    "title": "A Message to Our Customers",
    "user_id": "a0ee932b-14f5-494f-a0a6-ab3784c9a4b2",
    "user_name": "epaga",
    "created_at": "2016-02-17T08:38:37Z",
    "url_ref": "http://www.apple.com/customer-letter/",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In",
    "comment_count": 967,
    "upvote_count": 5771
  },
  {
    "id": "192125b9-1051-4852-9c69-54a0c4a77065",
    "title": "OpenAI's board has fired Sam Altman",
    "user_id": "2d6b803b-32c4-48a7-a52a-f8b9deddb001",
    "user_name": "davidbarker",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "https://openai.com/blog/openai-announces-leadership-transition",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta. Sed nec diam eu diam mattis viverra. Nulla fringilla, orci ac euismod semper, magna diam porttitor mauris, quis sollicitudin sapien justo in libero. Vestibulum mollis mauris enim.",
    "comment_count": 2531,
    "upvote_count": 5710
  },
  {
    "id": "id-0",
    "title": "Sample Title 0",
    "user_id": "user-0",
    "user_name": "user_name_0",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 1841,
    "upvote_count": 1079
  },
  {
    "id": "id-1",
    "title": "Sample Title 1",
    "user_id": "user-1",
    "user_name": "user_name_1",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/1",
    "content": null,
    "comment_count": 1143,
    "upvote_count": 4423
  },
  {
    "id": "id-2",
    "title": "Sample Title 2",
    "user_id": "user-2",
    "user_name": "user_name_2",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1132,
    "upvote_count": 3376
  },
  {
    "id": "id-3",
    "title": "Sample Title 3",
    "user_id": "user-3",
    "user_name": "user_name_3",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/3",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 1632,
    "upvote_count": 5638
  },
  {
    "id": "id-4",
    "title": "Sample Title 4",
    "user_id": "user-4",
    "user_name": "user_name_4",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 158,
    "upvote_count": 4800
  },
  {
    "id": "id-5",
    "title": "Sample Title 5",
    "user_id": "user-5",
    "user_name": "user_name_5",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/5",
    "content": null,
    "comment_count": 1220,
    "upvote_count": 1941
  },
  {
    "id": "id-6",
    "title": "Sample Title 6",
    "user_id": "user-6",
    "user_name": "user_name_6",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 590,
    "upvote_count": 3448
  },
  {
    "id": "id-7",
    "title": "Sample Title 7",
    "user_id": "user-7",
    "user_name": "user_name_7",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/7",
    "content": null,
    "comment_count": 745,
    "upvote_count": 2878
  },
  {
    "id": "id-8",
    "title": "Sample Title 8",
    "user_id": "user-8",
    "user_name": "user_name_8",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 593,
    "upvote_count": 6373
  },
  {
    "id": "id-9",
    "title": "Sample Title 9",
    "user_id": "user-9",
    "user_name": "user_name_9",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/9",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 667,
    "upvote_count": 3576
  },
  {
    "id": "id-10",
    "title": "Sample Title 10",
    "user_id": "user-10",
    "user_name": "user_name_10",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 212,
    "upvote_count": 6707
  },
  {
    "id": "id-11",
    "title": "Sample Title 11",
    "user_id": "user-11",
    "user_name": "user_name_11",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/11",
    "content": null,
    "comment_count": 1158,
    "upvote_count": 1241
  },
  {
    "id": "id-12",
    "title": "Sample Title 12",
    "user_id": "user-12",
    "user_name": "user_name_12",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 115,
    "upvote_count": 2197
  },
  {
    "id": "id-13",
    "title": "Sample Title 13",
    "user_id": "user-13",
    "user_name": "user_name_13",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/13",
    "content": null,
    "comment_count": 1534,
    "upvote_count": 3750
  },
  {
    "id": "id-14",
    "title": "Sample Title 14",
    "user_id": "user-14",
    "user_name": "user_name_14",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1061,
    "upvote_count": 5650
  },
  {
    "id": "id-15",
    "title": "Sample Title 15",
    "user_id": "user-15",
    "user_name": "user_name_15",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/15",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 1092,
    "upvote_count": 1553
  },
  {
    "id": "id-16",
    "title": "Sample Title 16",
    "user_id": "user-16",
    "user_name": "user_name_16",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1786,
    "upvote_count": 5201
  },
  {
    "id": "id-17",
    "title": "Sample Title 17",
    "user_id": "user-17",
    "user_name": "user_name_17",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/17",
    "content": null,
    "comment_count": 988,
    "upvote_count": 1459
  },
  {
    "id": "id-18",
    "title": "Sample Title 18",
    "user_id": "user-18",
    "user_name": "user_name_18",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 667,
    "upvote_count": 4282
  },
  {
    "id": "id-19",
    "title": "Sample Title 19",
    "user_id": "user-19",
    "user_name": "user_name_19",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/19",
    "content": null,
    "comment_count": 304,
    "upvote_count": 4420
  },
  {
    "id": "id-20",
    "title": "Sample Title 20",
    "user_id": "user-20",
    "user_name": "user_name_20",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1722,
    "upvote_count": 2254
  },
  {
    "id": "id-21",
    "title": "Sample Title 21",
    "user_id": "user-21",
    "user_name": "user_name_21",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/21",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 896,
    "upvote_count": 6795
  },
  {
    "id": "id-22",
    "title": "Sample Title 22",
    "user_id": "user-22",
    "user_name": "user_name_22",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1790,
    "upvote_count": 6527
  },
  {
    "id": "id-23",
    "title": "Sample Title 23",
    "user_id": "user-23",
    "user_name": "user_name_23",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/23",
    "content": null,
    "comment_count": 418,
    "upvote_count": 6120
  },
  {
    "id": "id-24",
    "title": "Sample Title 24",
    "user_id": "user-24",
    "user_name": "user_name_24",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 1877,
    "upvote_count": 4216
  },
  {
    "id": "id-25",
    "title": "Sample Title 25",
    "user_id": "user-25",
    "user_name": "user_name_25",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/25",
    "content": null,
    "comment_count": 1474,
    "upvote_count": 5242
  },
  {
    "id": "id-26",
    "title": "Sample Title 26",
    "user_id": "user-26",
    "user_name": "user_name_26",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1073,
    "upvote_count": 6190
  },
  {
    "id": "id-27",
    "title": "Sample Title 27",
    "user_id": "user-27",
    "user_name": "user_name_27",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/27",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 1105,
    "upvote_count": 1440
  },
  {
    "id": "id-28",
    "title": "Sample Title 28",
    "user_id": "user-28",
    "user_name": "user_name_28",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1992,
    "upvote_count": 2815
  },
  {
    "id": "id-29",
    "title": "Sample Title 29",
    "user_id": "user-29",
    "user_name": "user_name_29",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/29",
    "content": null,
    "comment_count": 1906,
    "upvote_count": 2018
  },
  {
    "id": "id-30",
    "title": "Sample Title 30",
    "user_id": "user-30",
    "user_name": "user_name_30",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 781,
    "upvote_count": 1669
  },
  {
    "id": "id-31",
    "title": "Sample Title 31",
    "user_id": "user-31",
    "user_name": "user_name_31",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/31",
    "content": null,
    "comment_count": 809,
    "upvote_count": 3174
  },
  {
    "id": "id-32",
    "title": "Sample Title 32",
    "user_id": "user-32",
    "user_name": "user_name_32",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 685,
    "upvote_count": 2467
  },
  {
    "id": "id-33",
    "title": "Sample Title 33",
    "user_id": "user-33",
    "user_name": "user_name_33",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/33",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 1027,
    "upvote_count": 2779
  },
  {
    "id": "id-34",
    "title": "Sample Title 34",
    "user_id": "user-34",
    "user_name": "user_name_34",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 840,
    "upvote_count": 1441
  },
  {
    "id": "id-35",
    "title": "Sample Title 35",
    "user_id": "user-35",
    "user_name": "user_name_35",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/35",
    "content": null,
    "comment_count": 679,
    "upvote_count": 6187
  },
  {
    "id": "id-36",
    "title": "Sample Title 36",
    "user_id": "user-36",
    "user_name": "user_name_36",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 1532,
    "upvote_count": 4068
  },
  {
    "id": "id-37",
    "title": "Sample Title 37",
    "user_id": "user-37",
    "user_name": "user_name_37",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/37",
    "content": null,
    "comment_count": 184,
    "upvote_count": 3525
  },
  {
    "id": "id-38",
    "title": "Sample Title 38",
    "user_id": "user-38",
    "user_name": "user_name_38",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 168,
    "upvote_count": 1573
  },
  {
    "id": "id-39",
    "title": "Sample Title 39",
    "user_id": "user-39",
    "user_name": "user_name_39",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/39",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 627,
    "upvote_count": 4429
  },
  {
    "id": "id-40",
    "title": "Sample Title 40",
    "user_id": "user-40",
    "user_name": "user_name_40",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 184,
    "upvote_count": 3330
  },
  {
    "id": "id-41",
    "title": "Sample Title 41",
    "user_id": "user-41",
    "user_name": "user_name_41",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/41",
    "content": null,
    "comment_count": 954,
    "upvote_count": 5605
  },
  {
    "id": "id-42",
    "title": "Sample Title 42",
    "user_id": "user-42",
    "user_name": "user_name_42",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 623,
    "upvote_count": 3231
  },
  {
    "id": "id-43",
    "title": "Sample Title 43",
    "user_id": "user-43",
    "user_name": "user_name_43",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/43",
    "content": null,
    "comment_count": 1243,
    "upvote_count": 4581
  },
  {
    "id": "id-44",
    "title": "Sample Title 44",
    "user_id": "user-44",
    "user_name": "user_name_44",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1906,
    "upvote_count": 2328
  },
  {
    "id": "id-45",
    "title": "Sample Title 45",
    "user_id": "user-45",
    "user_name": "user_name_45",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/45",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 355,
    "upvote_count": 3310
  },
  {
    "id": "id-46",
    "title": "Sample Title 46",
    "user_id": "user-46",
    "user_name": "user_name_46",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1851,
    "upvote_count": 5534
  },
  {
    "id": "id-47",
    "title": "Sample Title 47",
    "user_id": "user-47",
    "user_name": "user_name_47",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/47",
    "content": null,
    "comment_count": 1270,
    "upvote_count": 6677
  },
  {
    "id": "id-48",
    "title": "Sample Title 48",
    "user_id": "user-48",
    "user_name": "user_name_48",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 616,
    "upvote_count": 4958
  },
  {
    "id": "id-49",
    "title": "Sample Title 49",
    "user_id": "user-49",
    "user_name": "user_name_49",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/49",
    "content": null,
    "comment_count": 219,
    "upvote_count": 3708
  },
  {
    "id": "id-50",
    "title": "Sample Title 50",
    "user_id": "user-50",
    "user_name": "user_name_50",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1858,
    "upvote_count": 3416
  },
  {
    "id": "id-51",
    "title": "Sample Title 51",
    "user_id": "user-51",
    "user_name": "user_name_51",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/51",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 1820,
    "upvote_count": 4488
  },
  {
    "id": "id-52",
    "title": "Sample Title 52",
    "user_id": "user-52",
    "user_name": "user_name_52",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 796,
    "upvote_count": 3062
  },
  {
    "id": "id-53",
    "title": "Sample Title 53",
    "user_id": "user-53",
    "user_name": "user_name_53",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/53",
    "content": null,
    "comment_count": 530,
    "upvote_count": 3992
  },
  {
    "id": "id-54",
    "title": "Sample Title 54",
    "user_id": "user-54",
    "user_name": "user_name_54",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 246,
    "upvote_count": 1448
  },
  {
    "id": "id-55",
    "title": "Sample Title 55",
    "user_id": "user-55",
    "user_name": "user_name_55",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/55",
    "content": null,
    "comment_count": 248,
    "upvote_count": 6569
  },
  {
    "id": "id-56",
    "title": "Sample Title 56",
    "user_id": "user-56",
    "user_name": "user_name_56",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1904,
    "upvote_count": 5608
  },
  {
    "id": "id-57",
    "title": "Sample Title 57",
    "user_id": "user-57",
    "user_name": "user_name_57",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/57",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 1213,
    "upvote_count": 4156
  },
  {
    "id": "id-58",
    "title": "Sample Title 58",
    "user_id": "user-58",
    "user_name": "user_name_58",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1649,
    "upvote_count": 5308
  },
  {
    "id": "id-59",
    "title": "Sample Title 59",
    "user_id": "user-59",
    "user_name": "user_name_59",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/59",
    "content": null,
    "comment_count": 343,
    "upvote_count": 2282
  },
  {
    "id": "id-60",
    "title": "Sample Title 60",
    "user_id": "user-60",
    "user_name": "user_name_60",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 669,
    "upvote_count": 4758
  },
  {
    "id": "id-61",
    "title": "Sample Title 61",
    "user_id": "user-61",
    "user_name": "user_name_61",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/61",
    "content": null,
    "comment_count": 1650,
    "upvote_count": 1751
  },
  {
    "id": "id-62",
    "title": "Sample Title 62",
    "user_id": "user-62",
    "user_name": "user_name_62",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1553,
    "upvote_count": 4245
  },
  {
    "id": "id-63",
    "title": "Sample Title 63",
    "user_id": "user-63",
    "user_name": "user_name_63",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/63",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 1560,
    "upvote_count": 2499
  },
  {
    "id": "id-64",
    "title": "Sample Title 64",
    "user_id": "user-64",
    "user_name": "user_name_64",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 495,
    "upvote_count": 4595
  },
  {
    "id": "id-65",
    "title": "Sample Title 65",
    "user_id": "user-65",
    "user_name": "user_name_65",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/65",
    "content": null,
    "comment_count": 1710,
    "upvote_count": 2542
  },
  {
    "id": "id-66",
    "title": "Sample Title 66",
    "user_id": "user-66",
    "user_name": "user_name_66",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 435,
    "upvote_count": 2100
  },
  {
    "id": "id-67",
    "title": "Sample Title 67",
    "user_id": "user-67",
    "user_name": "user_name_67",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/67",
    "content": null,
    "comment_count": 758,
    "upvote_count": 3928
  },
  {
    "id": "id-68",
    "title": "Sample Title 68",
    "user_id": "user-68",
    "user_name": "user_name_68",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 951,
    "upvote_count": 4761
  },
  {
    "id": "id-69",
    "title": "Sample Title 69",
    "user_id": "user-69",
    "user_name": "user_name_69",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/69",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 1526,
    "upvote_count": 6922
  },
  {
    "id": "id-70",
    "title": "Sample Title 70",
    "user_id": "user-70",
    "user_name": "user_name_70",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1987,
    "upvote_count": 1079
  },
  {
    "id": "id-71",
    "title": "Sample Title 71",
    "user_id": "user-71",
    "user_name": "user_name_71",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/71",
    "content": null,
    "comment_count": 1027,
    "upvote_count": 1509
  },
  {
    "id": "id-72",
    "title": "Sample Title 72",
    "user_id": "user-72",
    "user_name": "user_name_72",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 1455,
    "upvote_count": 4454
  },
  {
    "id": "id-73",
    "title": "Sample Title 73",
    "user_id": "user-73",
    "user_name": "user_name_73",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/73",
    "content": null,
    "comment_count": 1493,
    "upvote_count": 2326
  },
  {
    "id": "id-74",
    "title": "Sample Title 74",
    "user_id": "user-74",
    "user_name": "user_name_74",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1726,
    "upvote_count": 1387
  },
  {
    "id": "id-75",
    "title": "Sample Title 75",
    "user_id": "user-75",
    "user_name": "user_name_75",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/75",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 1877,
    "upvote_count": 5863
  },
  {
    "id": "id-76",
    "title": "Sample Title 76",
    "user_id": "user-76",
    "user_name": "user_name_76",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 181,
    "upvote_count": 4412
  },
  {
    "id": "id-77",
    "title": "Sample Title 77",
    "user_id": "user-77",
    "user_name": "user_name_77",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/77",
    "content": null,
    "comment_count": 129,
    "upvote_count": 3596
  },
  {
    "id": "id-78",
    "title": "Sample Title 78",
    "user_id": "user-78",
    "user_name": "user_name_78",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 459,
    "upvote_count": 6617
  },
  {
    "id": "id-79",
    "title": "Sample Title 79",
    "user_id": "user-79",
    "user_name": "user_name_79",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/79",
    "content": null,
    "comment_count": 1188,
    "upvote_count": 2411
  },
  {
    "id": "id-80",
    "title": "Sample Title 80",
    "user_id": "user-80",
    "user_name": "user_name_80",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1329,
    "upvote_count": 4957
  },
  {
    "id": "id-81",
    "title": "Sample Title 81",
    "user_id": "user-81",
    "user_name": "user_name_81",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/81",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 725,
    "upvote_count": 4252
  },
  {
    "id": "id-82",
    "title": "Sample Title 82",
    "user_id": "user-82",
    "user_name": "user_name_82",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1445,
    "upvote_count": 3559
  },
  {
    "id": "id-83",
    "title": "Sample Title 83",
    "user_id": "user-83",
    "user_name": "user_name_83",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/83",
    "content": null,
    "comment_count": 1920,
    "upvote_count": 3135
  },
  {
    "id": "id-84",
    "title": "Sample Title 84",
    "user_id": "user-84",
    "user_name": "user_name_84",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 1317,
    "upvote_count": 4176
  },
  {
    "id": "id-85",
    "title": "Sample Title 85",
    "user_id": "user-85",
    "user_name": "user_name_85",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/85",
    "content": null,
    "comment_count": 314,
    "upvote_count": 5076
  },
  {
    "id": "id-86",
    "title": "Sample Title 86",
    "user_id": "user-86",
    "user_name": "user_name_86",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 954,
    "upvote_count": 5565
  },
  {
    "id": "id-87",
    "title": "Sample Title 87",
    "user_id": "user-87",
    "user_name": "user_name_87",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/87",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 619,
    "upvote_count": 2922
  },
  {
    "id": "id-88",
    "title": "Sample Title 88",
    "user_id": "user-88",
    "user_name": "user_name_88",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 873,
    "upvote_count": 3149
  },
  {
    "id": "id-89",
    "title": "Sample Title 89",
    "user_id": "user-89",
    "user_name": "user_name_89",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/89",
    "content": null,
    "comment_count": 1084,
    "upvote_count": 4720
  },
  {
    "id": "id-90",
    "title": "Sample Title 90",
    "user_id": "user-90",
    "user_name": "user_name_90",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 1398,
    "upvote_count": 2471
  },
  {
    "id": "id-91",
    "title": "Sample Title 91",
    "user_id": "user-91",
    "user_name": "user_name_91",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/91",
    "content": null,
    "comment_count": 1692,
    "upvote_count": 3286
  },
  {
    "id": "id-92",
    "title": "Sample Title 92",
    "user_id": "user-92",
    "user_name": "user_name_92",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1532,
    "upvote_count": 4370
  },
  {
    "id": "id-93",
    "title": "Sample Title 93",
    "user_id": "user-93",
    "user_name": "user_name_93",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/93",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 470,
    "upvote_count": 1854
  },
  {
    "id": "id-94",
    "title": "Sample Title 94",
    "user_id": "user-94",
    "user_name": "user_name_94",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 1184,
    "upvote_count": 4416
  },
  {
    "id": "id-95",
    "title": "Sample Title 95",
    "user_id": "user-95",
    "user_name": "user_name_95",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/95",
    "content": null,
    "comment_count": 1329,
    "upvote_count": 6628
  },
  {
    "id": "id-96",
    "title": "Sample Title 96",
    "user_id": "user-96",
    "user_name": "user_name_96",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 739,
    "upvote_count": 5038
  },
  {
    "id": "id-97",
    "title": "Sample Title 97",
    "user_id": "user-97",
    "user_name": "user_name_97",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/97",
    "content": null,
    "comment_count": 338,
    "upvote_count": 2026
  },
  {
    "id": "id-98",
    "title": "Sample Title 98",
    "user_id": "user-98",
    "user_name": "user_name_98",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": null,
    "content": null,
    "comment_count": 995,
    "upvote_count": 5705
  },
  {
    "id": "id-99",
    "title": "Sample Title 99",
    "user_id": "user-99",
    "user_name": "user_name_99",
    "created_at": "2023-11-17T20:28:50Z",
    "url_ref": "http://example.com/99",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta.",
    "comment_count": 474,
    "upvote_count": 5182
  }
];