import React from 'react';
import type { Metadata } from 'next';
import '@/styles/globals.css';
import { AuthContextProvider } from '@/features/auth/context/authProvider';

export const metadata: Metadata = {
	title: 'feed',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<AuthContextProvider>{children}</AuthContextProvider>
			</body>
		</html>
	);
}
